---
# tasks file for apigee-opdk-baas-silent-installation-config

- name: Construct the silent-install file
  template:
    src: 'baas-silent-install.conf.j2'
    dest: "{{ opdk_baas_silent_install_file_path }}"
    force: yes
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0644
  when: provided_response_file is not defined or not provided_response_file

- name: Copy provided silent-install file
  copy:
    src: "{{ opdk_baas_provided_silent_install_file }}"
    dest: "{{ opdk_baas_silent_install_file_path }}"
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0644
  when: provided_response_file is defined and provided_response_file
